# pnp，pnpm和node-modules
nodeLinker: pnp

# yarn dlx @yarnpkg/sdks 安装报错需要注释源
npmRegistryServer: "https://registry.npm.taobao.org/"

# 3.1.0
yarnPath: .yarn/releases/yarn-berry.cjs

plugins:
  - ./.yarn/plugins/hello.js
